# Free Energy Calculation Configuration - Sine-Cosine Dihedral CV
# Collective Variable Configuration
cv_type: "sin_cos_dihedral"

# CV-specific parameters
cv_params:
  # Dihedral atoms (C1-C2-C3-C4 carbons in butane)
  dihedral_atoms: [3, 6, 9, 13]
  
  # CV value ranges for both sin and cos of dihedral angle
  # Note: Both sin and cos have same range based on notebook
  cv_1_range: [-1.2, 1.2]  # Sin component
  cv_2_range: [-1.2, 1.2]  # Cos component

# Metadynamics parameters
metadynamics:
  bias_width: 0.08
  bias_factor: 10
  height: 0.1  # kJ/mol
  frequency: 100  # steps between bias addition
  grid_width: 1000

# Simulation parameters
simulation:
  temperature: 300  # Kelvin
  friction_coeff: 10  # ps^-1
  timestep: 2  # femtoseconds
  total_steps: 1000000
  platform: "CUDA"  # Options: "CUDA", "CPU", "OpenCL"

# System parameters
system:
  psf_file: "../butane/data/butane.psf"
  pdb_file: "../butane/data/butane.pdb"
  ff_rtf_file: "../butane/data/top_all35_ethers.rtf"
  ff_prm_file: "../butane/data/par_all35_ethers.prm"

# Output parameters
output:
  base_dir: "../butane/output/sin_cos_dihedral_TPT/"
  state_file: "state_metad.txt"
  trajectory_file: "traj_metad.dcd"
  free_energy_file: "free_energy.npz"
  cvs_file: "my_CVs.npz"
  params_file: "system_params.yml"
  report_frequency: 10
  console_report_frequency: 100000

# Device configuration
device: "cuda:0"
